name: activity-classification
channels:
  - defaults
dependencies:
  - numpy
  - scipy
  - scikit-learn
  - plotly
  - python=3.7
  - pytorch
  - pillow
  - matplotlib
  - pywavelets
  - h5py
  - tqdm

